import { PageTitle } from '@shared/ui'
import Quiz from 'react-quiz-component'
import styles from './styles.module.css'

const appLocale = {
  landingHeaderText: '<questionLength> вопросов',
  question: 'Вопрос',
  startQuizBtn: 'Начать',
  resultFilterAll: 'Все',
  resultFilterCorrect: 'Верно',
  resultFilterIncorrect: 'Неверно',
  prevQuestionBtn: 'Назад',
  nextQuestionBtn: 'Дальше',
  resultPageHeaderText:
    'Тестирование завершено. Вы ответили на <correctIndexLength> из <questionLength> вопросов.',
  resultPagePoint: '',
  pauseScreenDisplay: '',
  timerTimeRemaining: '',
  timerTimeTaken: '',
  pauseScreenPause: '',
  pauseScreenResume: '',
  singleSelectionTagText: '',
  multipleSelectionTagText: '',
  pickNumberOfSelection: '',
  marksOfQuestion: '',
}

export const quiz = {
  progressBarColor: '#9de1f6',
  appLocale,
  questions: [
    {
      question: 'Какую площадь занимает Россия?',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'Почти 17,1 миллиона квадратных километров',
        'Менее 10 миллионов квадратных километров',
        'Более 20 миллионов квадратных километров',
        '15 миллионов квадратных километров',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: 'Верно!',
      messageForIncorrectAnswer: 'Неверно!',
      point: '1',
    },
    {
      question: 'Сколько стран граничит с Россией?',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: ['10', '20', '14', '16'],
      correctAnswer: '4',
      messageForCorrectAnswer: 'Верно!',
      messageForIncorrectAnswer: 'Неверно!',
      point: '1',
    },
    {
      question: 'Какие климатические зоны отсутствуют на территории России?',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: ['Тропическая', 'Арктическая', 'Субтропическая', 'Умеренная'],
      correctAnswer: '1',
      messageForCorrectAnswer: 'Верно!',
      messageForIncorrectAnswer: 'Неверно!',
      point: '1',
    },
    {
      question: 'Сколько официально признанных языков в России?',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: ['70', 'Более 100', 'Менее 50', '150'],
      correctAnswer: '2',
      messageForCorrectAnswer: 'Верно!',
      messageForIncorrectAnswer: 'Неверно!',
      point: '1',
    },
    {
      question: 'Сколько народностей проживает в России?',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: ['Более 100', 'Более 200', 'Более 190', 'Меньше 200'],
      correctAnswer: '3',
      messageForCorrectAnswer: 'Верно!',
      messageForIncorrectAnswer: 'Неверно!',
      point: '1',
    },
    {
      question: 'Когда отмечается День России?',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: ['4 ноября', '1 января', '12 июня', '7 ноября'],
      correctAnswer: '3',
      messageForCorrectAnswer: 'Верно!',
      messageForIncorrectAnswer: 'Неверно!',
      point: '1',
    },
    {
      question: 'Какое озеро является крупнейшим по объему запасов пресной воды?',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: ['Каспийское море', 'Ладожское озеро', 'Онежское озеро', 'Байкал'],
      correctAnswer: '4',
      messageForCorrectAnswer: 'Верно!',
      messageForIncorrectAnswer: 'Неверно!',
      point: '1',
    },
    {
      question: 'Какая железнодорожная линия является самой длинной в мире?',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'Китайская железная дорога',
        'Железная дорога США',
        'Трансамериканская магистраль',
        'Транссибирская магистраль',
      ],
      correctAnswer: '4',
      messageForCorrectAnswer: 'Верно!',
      messageForIncorrectAnswer: 'Неверно!',
      point: '1',
    },
    {
      question: 'Сколько часовых поясов охватывает территория России?',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: ['7', '15', '5', '11'],
      correctAnswer: '4',
      messageForCorrectAnswer: 'Верно!',
      messageForIncorrectAnswer: 'Неверно!',
      point: '1',
    },
    {
      question: 'Сколько культурных и природных объектов в списке Всемирного наследия ЮНЕСКО?',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: ['Более 25', 'Более 20', 'Более 15', 'Более 10'],
      correctAnswer: '1',
      messageForCorrectAnswer: 'Верно!',
      messageForIncorrectAnswer: 'Неверно!',
      point: '1',
    },
    {
      question: 'В каком году Юрий Гагарин полетел в космос?',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: ['1945', '1957', '1969', '1961'],
      correctAnswer: '4',
      messageForCorrectAnswer: 'Верно!',
      messageForIncorrectAnswer: 'Неверно!',
      point: '1',
    },
    {
      question: 'Как принято обращаться к незнакомому человеку в России?',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: ['На "Вы"', 'На "ты"', 'Обращаться по имени', 'Использовать фамильярные обращения'],
      correctAnswer: '1',
      messageForCorrectAnswer: 'Верно!',
      messageForIncorrectAnswer: 'Неверно!',
      point: '1',
    },
    {
      question: 'Какие фразы обязательно нужно использовать при обращении к человеку?',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        '"Здравствуйте" и "До свидания"',
        'Эти фразы не обязательны',
        '"Здравствуй" и "Прощай"',
        '"Привет" и "Пока"',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: 'Верно!',
      messageForIncorrectAnswer: 'Неверно!',
      point: '1',
    },
    {
      question: 'Как следует благодарить человека за помощь в России?',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'Благодарность не обязательна',
        '"Огромное спасибо"',
        '"Спасибо" или "Благодарю Вас!"',
        '"Спасибо большое"',
      ],
      correctAnswer: '3',
      messageForCorrectAnswer: 'Верно!',
      messageForIncorrectAnswer: 'Неверно!',
      point: '1',
    },
    {
      question: 'Что запрещено делать в общественном транспорте в России?',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'Оплачивать проезд',
        'Держаться за поручни',
        'Уступать место пожилым людям',
        'Громко разговаривать по телефону',
      ],
      correctAnswer: '4',
      messageForCorrectAnswer: 'Верно!',
      messageForIncorrectAnswer: 'Неверно!',
      point: '1',
    },
    {
      question: 'Что является неприемлемым в России?',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'Обращение к незнакомцам на "Вы"',
        'Помощь незнакомым людям',
        'Демонстрация отношения к религии в общественных местах',
        'Ношение яркой одежды',
      ],
      correctAnswer: '3',
      messageForCorrectAnswer: 'Верно!',
      messageForIncorrectAnswer: 'Неверно!',
      point: '1',
    },
    {
      question: 'Какой город является столицей России и крупнейшим городом страны?',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: ['Санкт-Петербург', 'Москва', 'Новосибирск', 'Казань'],
      correctAnswer: '2',
      messageForCorrectAnswer: 'Верно!',
      messageForIncorrectAnswer: 'Неверно!',
      point: '1',
    },
    {
      question: 'Сколько жителей в Москве?',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: ['5,6 миллиона', '13,1 миллиона', '1,6 миллиона', '1,5 миллиона'],
      correctAnswer: '2',
      messageForCorrectAnswer: 'Верно!',
      messageForIncorrectAnswer: 'Неверно!',
      point: '1',
    },
    {
      question: 'Какой памятник архитектуры находится в Санкт-Петербурге?',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: ['Спасская башня', 'Эрмитаж', 'Кремль', 'Храм Василия Блаженного'],
      correctAnswer: '2',
      messageForCorrectAnswer: 'Верно!',
      messageForIncorrectAnswer: 'Неверно!',
      point: '1',
    },
    {
      question: 'Какой город называют столицей Сибири?',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: ['Екатеринбург', 'Красноярск', 'Новосибирск', 'Челябинск'],
      correctAnswer: '3',
      messageForCorrectAnswer: 'Верно!',
      messageForIncorrectAnswer: 'Неверно!',
      point: '1',
    },
    {
      question: 'Сколько жителей в Екатеринбурге?',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: ['1,2 миллиона', '1,5 миллиона', '1,3 миллиона', '1,6 миллиона'],
      correctAnswer: '2',
      messageForCorrectAnswer: 'Верно!',
      messageForIncorrectAnswer: 'Неверно!',
      point: '1',
    },
    {
      question: 'Какой город является столицей Татарстана?',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: ['Челябинск', 'Казань', 'Уфа', 'Самара'],
      correctAnswer: '2',
      messageForCorrectAnswer: 'Верно!',
      messageForIncorrectAnswer: 'Неверно!',
      point: '1',
    },
    {
      question: 'Какой из перечисленных городов имеет одну из самых длинных набережных в России?',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: ['Самара', 'Нижний Новгород', 'Красноярск', 'Омск'],
      correctAnswer: '1',
      messageForCorrectAnswer: 'Верно!',
      messageForIncorrectAnswer: 'Неверно!',
      point: '1',
    },
    {
      question: 'Какой памятник находится в Уфе?',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'Памятник Салавату Юлаеву',
        'Ростральные колонны',
        'Исаакиевский собор',
        'Храм Василия Блаженного',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: 'Верно!',
      messageForIncorrectAnswer: 'Неверно!',
      point: '1',
    },
    {
      question: 'Сколько жителей в Казани?',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: ['1,6 миллиона', '1,3 миллиона', '1,2 миллиона', '1,5 миллиона'],
      correctAnswer: '2',
      messageForCorrectAnswer: 'Верно!',
      messageForIncorrectAnswer: 'Неверно!',
      point: '1',
    },
    {
      question: 'Какой город находится на стрелке Волги и Оки?',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: ['Красноярск', 'Челябинск', 'Нижний Новгород', 'Екатеринбург'],
      correctAnswer: '3',
      messageForCorrectAnswer: 'Верно!',
      messageForIncorrectAnswer: 'Неверно!',
      point: '1',
    },
    {
      question: 'В каком году на Руси приняли крещение?',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: ['987', '998', '988', '968'],
      correctAnswer: '3',
      messageForCorrectAnswer: 'Верно!',
      messageForIncorrectAnswer: 'Неверно!',
      point: '1',
    },
    {
      question: 'Сколько длилось нашествие монголо-татарского ига на Русь?',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: ['Более 250 лет', 'Более 200', 'Более 150 лет', 'Более 300'],
      correctAnswer: '1',
      messageForCorrectAnswer: 'Верно!',
      messageForIncorrectAnswer: 'Неверно!',
      point: '1',
    },
    {
      question: 'Считается ли Ростов-на-Дону городом-миллионником?',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: ['Да', 'Нет'],
      correctAnswer: '1',
      messageForCorrectAnswer: 'Верно!',
      messageForIncorrectAnswer: 'Неверно!',
      point: '1',
    },
    {
      question: 'Россия простирается на два континента — Европу и Азию, разделённая какими горами?',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: ['Уральскими горами', 'Гимолаи', 'Эльбрус', 'Ключевская Сопка'],
      correctAnswer: '1',
      messageForCorrectAnswer: 'Верно!',
      messageForIncorrectAnswer: 'Неверно!',
      point: '1',
    },
  ],
}

export const AboutRussia5Page = () => {
    return (
        <>
            <PageTitle text={'Тестирование 1'}/>

            <div className={styles.test}>
                <Quiz quiz={quiz} disableSynopsis/>
            </div>
        </>
    )
}