import Quiz from 'react-quiz-component'

import { PageTitle } from '@shared/ui'

import styles from './styles.module.css'

const appLocale = {
  landingHeaderText: '<questionLength> вопросов',
  question: 'Вопрос',
  startQuizBtn: 'Начать',
  resultFilterAll: 'Все',
  resultFilterCorrect: 'Верно',
  resultFilterIncorrect: 'Неверно',
  prevQuestionBtn: 'Назад',
  nextQuestionBtn: 'Дальше',
  resultPageHeaderText:
    'Тестирование завершено. Вы ответили на <correctIndexLength> из <questionLength> вопросов.',
  resultPagePoint: '',
  pauseScreenDisplay: '',
  timerTimeRemaining: '',
  timerTimeTaken: '',
  pauseScreenPause: '',
  pauseScreenResume: '',
  singleSelectionTagText: '',
  multipleSelectionTagText: '',
  pickNumberOfSelection: '',
  marksOfQuestion: '',
}

export const quiz = {
  progressBarColor: '#9de1f6',
  appLocale,
  questions: [
    {
      question: 'Какой документ необходим иностранным гражданам для въезда в Российскую Федерацию?',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: ['Заграничный паспорт', 'Виза', 'Удостоверение личности', 'Справка о несудимости'],
      correctAnswer: '2',
      messageForCorrectAnswer: 'Верно!',
      messageForIncorrectAnswer: 'Неверно!',
      point: '1',
    },
    {
      question: 'Какой тип визы не предусмотрен для иностранных граждан?',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: ['Дипломатическая', 'Рабочая', 'Спортивная', 'Транзитная'],
      correctAnswer: '3',
      messageForCorrectAnswer: 'Верно!',
      messageForIncorrectAnswer: 'Неверно!',
      point: '1',
    },
    {
      question: 'Что включает в себя виза?',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'Только имя и фамилию',
        'Фотографию и дату выдачи',
        'Все перечисленные сведения',
        'Только срок действия',
      ],
      correctAnswer: '3',
      messageForCorrectAnswer: 'Верно!',
      messageForIncorrectAnswer: 'Неверно!',
      point: '1',
    },
    {
      question: 'Какой срок действия визы устанавливается?',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'Только в соответствии с международными договорами',
        'В соответствии с Федеральным законом',
        'По усмотрению консульства',
        'В зависимости от страны происхождения',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: 'Верно!',
      messageForIncorrectAnswer: 'Неверно!',
      point: '1',
    },
    {
      question: 'Кто выдает визы временно проживающего лица?',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'Министерство иностранных дел',
        'Территориальные органы МВД России',
        'Федеральная миграционная служба',
        'Посольства иностранных государств',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: 'Верно!',
      messageForIncorrectAnswer: 'Неверно!',
      point: '1',
    },
    {
      question: 'Какой документ должен быть представлен для получения транзитной визы?',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'Заграничный паспорт',
        'Проездной билет',
        'Справка о доходах',
        'Свидетельство о рождении',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: 'Верно!',
      messageForIncorrectAnswer: 'Неверно!',
      point: '1',
    },
    {
      question: 'Какой размер государственной пошлины за оформление обыкновенной рабочей визы?',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: ['500 рублей', '1000 рублей', '1500 рублей', '2000 рублей'],
      correctAnswer: '3',
      messageForCorrectAnswer: 'Верно!',
      messageForIncorrectAnswer: 'Неверно!',
      point: '1',
    },
    {
      question:
        'Какой срок составляет максимальный период для предоставления государственной услуги?',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: ['10 рабочих дней', '15 рабочих дней', '20 рабочих дней', '30 рабочих дней'],
      correctAnswer: '3',
      messageForCorrectAnswer: 'Верно!',
      messageForIncorrectAnswer: 'Неверно!',
      point: '1',
    },
    {
      question: 'Какой документ удостоверяет личность представителя при подаче анкеты?',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'Заграничный паспорт',
        'Удостоверение личности',
        'Свидетельство о рождении',
        'Виза',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: 'Верно!',
      messageForIncorrectAnswer: 'Неверно!',
      point: '1',
    },
    {
      question: 'Что должно быть сделано в случае, если в визе обнаружены ошибки?',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'Виза аннулируется',
        'Ошибки не исправляются',
        'Виза остается без изменений',
        'Заявитель получает новый паспорт',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: 'Верно!',
      messageForIncorrectAnswer: 'Неверно!',
      point: '1',
    },
    {
      question:
        'Какой документ подтверждает статус постоянно проживающего иностранного гражданина в РФ?',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: ['Заграничный паспорт', 'Виза', 'Вид на жительство', 'Разрешение на работу'],
      correctAnswer: '3',
      messageForCorrectAnswer: 'Верно!',
      messageForIncorrectAnswer: 'Неверно!',
      point: '1',
    },
    {
      question: 'Какое право не имеет постоянно проживающий в РФ иностранный гражданин?',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'Право на медицинскую помощь',
        'Право на участие в выборах',
        'Право на трудовую деятельность без разрешения',
        'Право на пенсию',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: 'Верно!',
      messageForIncorrectAnswer: 'Неверно!',
      point: '1',
    },
    {
      question:
        'Какой срок необходимо соблюдать для регистрации по месту жительства после получения вида на жительство?',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: ['3 рабочих дня', '5 рабочих дней', '7 рабочих дней', '10 рабочих дней'],
      correctAnswer: '3',
      messageForCorrectAnswer: 'Верно!',
      messageForIncorrectAnswer: 'Неверно!',
      point: '1',
    },
    {
      question: 'Какой документ необходимо предоставить при регистрации по месту жительства?',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'Справка о доходах',
        'Удостоверение личности',
        'Свидетельство о браке',
        'Заграничный паспорт',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: 'Верно!',
      messageForIncorrectAnswer: 'Неверно!',
      point: '1',
    },
    {
      question: 'Какой из следующих документов не требуется для получения разрешения на работу?',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'Вид на жительство',
        'Миграционная карта',
        'Удостоверение личности',
        'Справка о несудимости',
      ],
      correctAnswer: '3',
      messageForCorrectAnswer: 'Верно!',
      messageForIncorrectAnswer: 'Неверно!',
      point: '1',
    },
    {
      question: 'Как часто иностранный гражданин должен уведомлять о своем проживании в РФ?',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: ['Каждый месяц', 'Каждые полгода', 'Каждый год', 'Каждые пять лет'],
      correctAnswer: '3',
      messageForCorrectAnswer: 'Верно!',
      messageForIncorrectAnswer: 'Неверно!',
      point: '1',
    },
    {
      question:
        'Какой из следующих пунктов не является обязанностью постоянно проживающего иностранного гражданина?',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'Заполнение миграционной карты',
        'Уведомление о месте жительства',
        'Оплата налогов',
        'Участие в выборах',
      ],
      correctAnswer: '1',
      messageForCorrectAnswer: 'Верно!',
      messageForIncorrectAnswer: 'Неверно!',
      point: '1',
    },
    {
      question: 'Кто может быть членом политической партии на территории РФ?',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'Постоянно проживающие иностранцы',
        'Временные иностранцы',
        'Российские граждане',
        'Все иностранцы',
      ],
      correctAnswer: '3',
      messageForCorrectAnswer: 'Верно!',
      messageForIncorrectAnswer: 'Неверно!',
      point: '1',
    },
    {
      question:
        'Какой срок составляет максимальный период для подачи уведомления о подтверждении проживания в РФ после получения вида на жительство?',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: ['1 месяц', '2 месяца', '6 месяцев', '1 год'],
      correctAnswer: '3',
      messageForCorrectAnswer: 'Верно!',
      messageForIncorrectAnswer: 'Неверно!',
      point: '1',
    },
    {
      question:
        'Какой документ подтверждает право иностранного гражданина на временную работу в РФ?',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: ['Виза', 'Разрешение на работу', 'Вид на жительство', 'Миграционная карта'],
      correctAnswer: '2',
      messageForCorrectAnswer: 'Верно!',
      messageForIncorrectAnswer: 'Неверно!',
      point: '1',
    },
    {
      question:
        'Какое минимальное время необходимо непрерывно проживать в России для получения гражданства?',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: ['3 года', '5 лет', '7 лет', '10 лет'],
      correctAnswer: '2',
      messageForCorrectAnswer: 'Верно!',
      messageForIncorrectAnswer: 'Неверно!',
      point: '1',
    },
    {
      question: 'Какой язык необходимо знать для получения гражданства РФ?',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: ['Английский', 'Русский', 'Французский', 'Немецкий'],
      correctAnswer: '2',
      messageForCorrectAnswer: 'Верно!',
      messageForIncorrectAnswer: 'Неверно!',
      point: '1',
    },
    {
      question: 'Куда следует подавать заявление на получение гражданства?',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'В Федеральную миграционную службу',
        'В Министерство внутренних дел Российской Федерации (МВД)',
        'В Министерство иностранных дел',
        'В местную администрацию',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: 'Верно!',
      messageForIncorrectAnswer: 'Неверно!',
      point: '1',
    },
    {
      question: 'Какой документ подтверждает право на постоянное проживание в России?',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: ['Виза', 'Вид на жительство', 'Заграничный паспорт', 'Свидетельство о рождении'],
      correctAnswer: '2',
      messageForCorrectAnswer: 'Верно!',
      messageForIncorrectAnswer: 'Неверно!',
      point: '1',
    },
    {
      question: 'Кто может подать заявление на получение гражданства за своего ребенка?',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: ['Только отец', 'Только мать', 'Оба родителя или опекун', 'Любой родственник'],
      correctAnswer: '3',
      messageForCorrectAnswer: 'Верно!',
      messageForIncorrectAnswer: 'Неверно!',
      point: '1',
    },
    {
      question:
        'Какой документ не требуется для получения гражданства для иностранных граждан старше 70 лет?',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'Паспорт',
        'Документ о знании русского языка',
        'Свидетельство о рождении',
        'Вид на жительство',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: 'Верно!',
      messageForIncorrectAnswer: 'Неверно!',
      point: '1',
    },
    {
      question:
        'Какой срок дается для подачи заявления о гражданстве после получения вида на жительство?',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: ['1 месяц', '6 месяцев', '1 год', '5 лет'],
      correctAnswer: '2',
      messageForCorrectAnswer: 'Верно!',
      messageForIncorrectAnswer: 'Неверно!',
      point: '1',
    },
    {
      question: 'Что должно быть указано в заявлении на получение гражданства?',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'Только имя и фамилия',
        'Все графы, обязательные к заполнению',
        'Только адрес проживания',
        'Необходимость указания места работы',
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: 'Верно!',
      messageForIncorrectAnswer: 'Неверно!',
      point: '1',
    },
    {
      question: 'Какой сертификат необходимо предоставить для подтверждения знания истории России?',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'Сертификат о владении русским языком',
        'Сертификат об образовании',
        'Сертификат о знании истории и основ законодательства РФ',
        'Сертификат о трудовом стаже',
      ],
      correctAnswer: '3',
      messageForCorrectAnswer: 'Верно!',
      messageForIncorrectAnswer: 'Неверно!',
      point: '1',
    },
    {
      question: 'Какой документ подтверждает отсутствие гражданства у заявителя?',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'Паспорт',
        'Удостоверение личности',
        'Документ, выданный полномочным органом иностранного государства',
        'Свидетельство о смерти',
      ],
      correctAnswer: '3',
      messageForCorrectAnswer: 'Верно!',
      messageForIncorrectAnswer: 'Неверно!',
      point: '1',
    },
  ],
}

export const Laws5Page = () => {
  return (
    <>
      <PageTitle text={'Тестирование'} />

      <div className={styles.test}>
        <Quiz quiz={quiz} disableSynopsis />
      </div>
    </>
  )
}
